### ISSUE TITLE
移除项目无关文件

### ISSUE THREAD

**Issue by Cyl18** [Chianne1025/QQChannelFramework#1]
.DS_Store 和 .vs 文件夹和项目无关 应该被排除

vs 的 .gitignore 可以用 <https://github.com/github/gitignore/blob/master/VisualStudio.gitignore>
这里的再加上一行 .DS_Store

再把项目里已有的 .vs 文件夹和 .DS_Store 删掉

**Comment by Cheyenne1025** [comment]
收到
