### ISSUE TITLE
[建议] 不要使用 Console.WriteLine 输出调试内容

### ISSUE THREAD

**Issue by Cyl18** [Chianne1025/QQChannelFramework#2]
https://github.com/Chianne1025/QQChannelFramework/blob/97f79fd40d876b9c7c6a92b5a0f2fd3a1ee0651c/Api/MessageApi.cs#L203
不要使用 Console.WriteLine 输出调试内容, 会污染用这个库的控制台程序的输出(((

**Comment by Cheyenne1025** [comment]
🙏感谢提醒，这个应该清理的时候漏掉了

**Comment by Cheyenne1025** [comment]
已解决
