### ISSUE TITLE
[建议] 为每个异步调用后面加上 .ConfigureAwait(false)

### ISSUE THREAD

**Issue by Cyl18** [Chianne1025/QQChannelFramework#3]
参考 <https://blog.walterlv.com/post/using-configure-await-to-avoid-deadlocks.html>, API 类库都应该使用 `.ConfigureAwait(false)`
看过 .NET 标准库 里面所有 await 后面必有 .ConfigureAwait(false)

**Comment by Cheyenne1025** [comment]
感谢大佬，新知识增加，这就改！！
