### ISSUE TITLE
不要使用 .Result

### ISSUE THREAD

**Issue by Cyl18** [Chianne1025/QQChannelFramework#5]
https://github.com/Chianne1025/QQChannelFramework/blob/c53e33f7f26a28daeeccea65e1d4a76ae57b4d18/Api/Base/ApiBase.cs#L127
应用 await 代替

**Comment by Cheyenne1025** [comment]
正在调查，当时使用await之后无法正确接收结果，反而.Result直接获取结果是能正常运行
